services:
  postgres:
    container_name: postgres-deployment
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=q1w2e3r4
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    restart: always

  pgadmin:
    container_name: pgadmin-deployment
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=teste@teste.com
      - PGADMIN_DEFAULT_PASSWORD=q1w2e3r4
    ports:
      - "5050:80"
    restart: always
